// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Client = {};

var Result = {};

var ListObjectsCommand = {
  Result: Result
};

var Result$1 = {};

var DeleteObjectCommand = {
  Result: Result$1
};

exports.Client = Client;
exports.ListObjectsCommand = ListObjectsCommand;
exports.DeleteObjectCommand = DeleteObjectCommand;
/* No side effect */
