// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Aws_Common = require("./Aws_Common.res.js");

Aws_Common.ls("Production").then(function (files) {
      files.forEach(function (file) {
            console.log(file);
          });
    });

/*  Not a pure module */
