// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Aws_Common = require("./Aws_Common.res.js");
var Promises = require("fs/promises");

Promises.copyFile(Aws_Common.basePath + "/.env-dev", Aws_Common.dotEnvFilePath).then(function () {
      console.log(".env file prepared for DEV");
    });

/*  Not a pure module */
