// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Aws_Common = require("./Aws_Common.res.js");

Aws_Common.rm("Development").then(function () {
      return Aws_Common.cp("Development");
    });

/*  Not a pure module */
