### Save
POST {{url}}/project
Accept: application/json
Authorization: Bearer {{$auth.token("cognito")}}
Content-Type: application/json

#< ./body/project/mindwork.json
#< ./body/project/between-the-planets.json
< ./body/project/voice-of-instinct.json

### Get
GET {{url}}/project/Mindwork
Accept: application/json
Authorization: Bearer {{$auth.token("cognito")}}
Content-Type: application/json

### Delete
DELETE {{url}}/project/Voice Of Instinct
Accept: application/json
Authorization: Bearer {{$auth.token("cognito")}}
Content-Type: application/json

### GetAll
GET {{url}}/project
Accept: application/json
Authorization: Bearer {{$auth.token("cognito")}}
Content-Type: application/json
