org: morbo
app: practice-tool-rescript
service: practice-tool-rescript
frameworkVersion: "4"

stages:
  dev:
    observability: false
    params:
      origins:
        - https://dev.practice-tool.click
        - http://localhost:3000
  prod:
    observability: false
    params:
      origins:
        - https://www.practice-tool.click

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  userPoolId: ${self:provider.region}_NWWCPvxRL
  userPoolClientId: 5l72lsb5di0lrft25llng18vl0
  tableNameProjects: ${self:service}-projects-${self:custom.currentStage}
  tableNameHistory: ${self:service}-history-${self:custom.currentStage}

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: ${self:custom.currentStage}
  environment:
    TABLE_NAME_PROJECTS: ${self:custom.tableNameProjects}
    TABLE_NAME_HISTORY: ${self:custom.tableNameHistory}
  httpApi:
    cors:
      allowedOrigins: ${param:origins}
    authorizers:
      practiceToolAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:custom.userPoolId}
        audience:
          - ${self:custom.userPoolClientId}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:Query
          Resource: "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.tableNameProjects}"
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.tableNameHistory}"

functions:
  saveProject:
    handler: index.projectLambdaSave
    events:
      - httpApi:
          path: /project
          method: POST
          authorizer:
            name: practiceToolAuthorizer
            scopes:
              - openid
              - profile
              - email
  getProject:
    handler: index.projectLambdaGet
    events:
      - httpApi:
          path: /project/{name}
          method: GET
          authorizer:
            name: practiceToolAuthorizer
            scopes:
              - openid
              - profile
              - email
  deleteProject:
    handler: index.projectLambdaDelete
    events:
      - httpApi:
          path: /project/{name}
          method: DELETE
          authorizer:
            name: practiceToolAuthorizer
            scopes:
              - openid
              - profile
              - email
  getAllProjects:
    handler: index.projectLambdaGetAll
    events:
      - httpApi:
          path: /project
          method: GET
          authorizer:
            name: practiceToolAuthorizer
            scopes:
              - openid
              - profile
              - email
  getPracticeSession:
    handler: index.sessionLambdaGet
    events:
      - httpApi:
          path: /session/{projectName}/{exerciseCount}
          method: GET
          authorizer:
            name: practiceToolAuthorizer
            scopes:
              - openid
              - profile
              - email
  savePracticeSession:
    handler: index.sessionLambdaSave
    events:
      - httpApi:
          path: /session
          method: POST
          authorizer:
            name: practiceToolAuthorizer
            scopes:
              - openid
              - profile
              - email

resources:
  Resources:
    PracticeToolProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNameProjects}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: name
            AttributeType: S
    PracticeToolHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNameHistory}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: date
            AttributeType: S
