org: morbo
app: practice-tool-rescript
service: practice-tool-rescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: ${self:custom.currentStage}
  httpApi:
    authorizers:
      practiceToolAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:custom.userPoolId}
        audience:
          - ${self:custom.userPoolClientId}

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  userPoolId: ${self:provider.region}_NWWCPvxRL
  userPoolClientId: 5l72lsb5di0lrft25llng18vl0


functions:
  helloWorld:
    handler: src/project/SaveProjectLambda.res.handler
    events:
      - httpApi:
          path: /project/save
          method: POST
          authorizer:
            name: practiceToolAuthorizer
            scopes:
              - openid
              - profile
              - email

resources:
  Resources:
    PracticeToolProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-projects-${self:custom.currentStage}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: user-id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: user-id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
    PracticeToolHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-history-${self:custom.currentStage}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: user-id
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: user-id
            AttributeType: S
          - AttributeName: date
            AttributeType: S
