org: morbo
app: practice-tool-rescript
service: practice-tool-rescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: ${self:custom.currentStage}
  httpApi:
    authorizers:
      practiceToolAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:custom.userPoolId}
        audience:
          - ${self:custom.userPoolClientId}

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  userPoolId: ${self:provider.region}_NWWCPvxRL
  userPoolClientId: 5l72lsb5di0lrft25llng18vl0


functions:
  helloWorld:
    handler: src/HelloWorld.res.handler
    events:
      - httpApi:
          path: /
          method: get
          authorizer:
            name: practiceToolAuthorizer
            scopes:
              - openid
              - email

resources:
  Resources:
    PracticeToolTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: environment
            AttributeType: S
          - AttributeName: id
            AttributeType: S
          - AttributeName: context
            AttributeType: S
        KeySchema:
          - AttributeName: environment
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: environment-context-index
            KeySchema:
              - AttributeName: environment
                KeyType: HASH
              - AttributeName: context
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
