// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


async function handler(param, param$1, param$2) {
  return {
          statusCode: 200,
          body: JSON.stringify(Object.fromEntries([[
                      "john",
                      "doe"
                    ]]))
        };
}

exports.handler = handler;
/* No side effect */
